import { NextResponse } from 'next/server';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { readSession } from '@/lib/session';
import { documentsRoot, heldApplications } from '@/lib/applications';

/**
 * Serving one piece of an applicant's evidence to a reviewer.
 *
 * These are certificates of incorporation, tax certificates and photo ID of a
 * named person. They are not public, and they are not served from a static
 * folder — every read passes through this handler so that being a platform
 * owner is checked first.
 *
 * The path is never built from anything the caller sent. The request names a
 * document by its id, that id is looked up on the application, and the stored
 * path comes from the record. A caller who invents a `documentId` finds
 * nothing, and one who sends `../../etc/passwd` finds nothing either, because
 * their string is only ever compared, never joined onto a path.
 */
export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string; documentId: string }> },
) {
  const session = await readSession();
  if (!session || session.accountType !== 'platform_owner') {
    // No distinction between "not signed in" and "not allowed": a reviewer's
    // queue should not be enumerable by anybody who can send a request.
    return NextResponse.json({ error: 'Not found.' }, { status: 404 });
  }

  const { id, documentId } = await context.params;
  const application = (await heldApplications()).find((row) => row.id === id);
  const document = application?.onboarding?.documents.find((d) => d.id === documentId);
  if (!document) {
    return NextResponse.json({ error: 'Not found.' }, { status: 404 });
  }

  /*
   * Belt and braces on the stored path.
   *
   * `storedAs` is generated by the upload handler and never taken from a
   * filename, so it cannot escape the folder. This re-checks anyway: the store
   * is a JSON file on disk, and a module that reads files should not depend on
   * every writer of that file having been careful.
   */
  const root = documentsRoot();
  const target = path.resolve(root, document.storedAs);
  if (!target.startsWith(path.resolve(root) + path.sep)) {
    return NextResponse.json({ error: 'Not found.' }, { status: 404 });
  }

  let bytes: Buffer;
  try {
    bytes = await readFile(target);
  } catch {
    return NextResponse.json({ error: 'That file is no longer on disk.' }, { status: 410 });
  }

  return new NextResponse(new Uint8Array(bytes), {
    headers: {
      'Content-Type': document.contentType,
      /*
       * `inline` so a reviewer sees the certificate rather than downloading it,
       * with the applicant's own filename attached so it is recognisable. The
       * name is quoted and stripped of quotes and newlines, which are the two
       * things that would let it break out of this header.
       */
      'Content-Disposition': `inline; filename="${document.fileName.replace(/["\r\n]/g, '')}"`,
      // Evidence about a named individual. Never cached by anything in between.
      'Cache-Control': 'private, no-store',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
